backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "events"
    label: "Events"
    folder: "src/pages/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "event-item",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Event Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Featured Event",
          name: "featuredEvent",
          widget: "boolean",
          default: false,
        }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Address", name: "address", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Info Text, name: infoText, widget: list }
          - { label: Image, name: image, widget: image }
          - {
              label: Current Semon Image (optional),
              name: currentSermonImage,
              widget: image,
            }
          - { label: Logo, name: logo, widget: image }
          - {
              label: "Mission Statement",
              name: missionStatement,
              widget: string,
            }
          - {
              label: "Mission Substatement",
              name: missionSubStatement,
              widget: string,
            }
          - {
              label: Announcement Title,
              name: announcementTitle,
              widget: string,
            }
          - {
              label: Show Announcements,
              name: showAnnouncements,
              widget: boolean,
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: subtitle, widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/im-new/index.md"
        label: "I'm New"
        name: "im-new"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "im-new-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: subtitle, widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: Items,
              name: items,
              widget: list,
              fields:
                [
                  { label: Lead, name: lead, widget: string },
                  { label: Text, name: text, widget: text },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: "src/pages/beliefs/index.md"
        label: "Beliefs Page"
        name: "beliefs"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "beliefs-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/credits/index.md"
        label: "Credits Page"
        name: "credits"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "credits-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Credits, name: credits, widget: list, allow_add: true }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/give/index.md"
        label: "Give Page"
        name: "give"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "give-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/leadership/index.md"
        label: "Leadership Page"
        name: "leadership"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "leadership-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - {
              label: Staff,
              name: staff,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: Subtitle, name: subtitle, widget: string },
                  { label: Bio, name: bio, widget: text },
                  { label: Image, name: image, widget: image },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/announcements/index.md"
        label: "Announcements Page"
        name: "announcements"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "announcements-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/_footer.md"
        label: "Footer"
        name: "footer"
        fields:
          - { label: "Name", name: "name", widget: "hidden", default: "footer" }
          - {
              label: "Type",
              name: "type",
              widget: "hidden",
              default: "page-content",
            }
          - { label: Services, name: services, widget: list }
          - { label: Phone Number, name: phoneNumber, widget: string }
          - { label: Email Address, name: emailAddress, widget: string }
          - { label: Address - Line 1, name: addressLineOne, widget: string }
          - { label: Address - Line 2, name: addressLineTwo, widget: string }
          - { label: Google Maps Link, name: googleMapsLink, widget: string }
          - {
              label: Facebook Link,
              name: facebookLink,
              widget: string,
              required: false,
            }
          - {
              label: Twitter Link,
              name: twitterLink,
              widget: string,
              required: false,
            }
          - {
              label: Instagram Link,
              name: instagramLink,
              widget: string,
              required: false,
            }
          - {
              label: YouTube Link,
              name: youtubeLink,
              widget: string,
              required: false,
            }
          - {
              label: Vimeo Link,
              name: vimeoLink,
              widget: string,
              required: false,
            }
